name: llama_flow
description: "NO Code RAG workflow"

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cross_file: ^0.3.4+1
  desktop_drop: ^0.4.4
  dio: ^5.4.3+1
  dynamic_base_url: ^1.2.1
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.12
  flutter_localizations:
    sdk: flutter
  flutter_tabler_icons: ^1.27.0
  google_fonts: ^6.2.1
  google_geocoding_api: ^1.5.2
  ionicons: ^0.2.2
  loading_indicator_view_plus: ^2.0.0
  provider: ^6.1.2
  side_sheet_material3: ^0.0.2
  sidebarx: ^0.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
