///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class VectorDBCollectionModel {
/*
{
  "name": "default",
  "id": "ec9b251d-ab95-4781-b0fb-72fcaff5fc48",
  "metadata": null,
  "tenant": "default_tenant",
  "database": "default_database"
} 
*/

  String? name;
  String? id;
  String? metadata;
  String? tenant;
  String? database;

  VectorDBCollectionModel({
    this.name,
    this.id,
    this.metadata,
    this.tenant,
    this.database,
  });
  VectorDBCollectionModel.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    id = json['id']?.toString();
    metadata = json['metadata']?.toString();
    tenant = json['tenant']?.toString();
    database = json['database']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['id'] = id;
    data['metadata'] = metadata;
    data['tenant'] = tenant;
    data['database'] = database;
    return data;
  }
}
