display_name: llama_flow
package_name: llama-flow

maintainer:
  name: Sabeerali KP
  email: sabeeralikp233@gmail.com

priority: optional

section: x11

installed_size: 15700

dependencies:
  - mpv

essential: false

icon: linux/assets/llama_flow.jpg

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - llama_flow
  - Llama_Flow

generic_name: llama_flow

categories:
  - Development
  - Utility

startup_notify: true
